// The deck's single source of truth. Change a number here, then start a new game.
export const CARD_COUNTS = {
  peasant: 7,
  knight: 3,
  lord: 2,
  lady: 2,
  warhorse: 2,
  weapon_bearer: 2,
  monk: 4,
  episcop: 1,
  preacher: 1,
  inquisitor: 1,
  plague_doc: 5,
  witch: 2,
  executioner: 2,
  troubadur: 1,
  merchant: 2,
  recruit: 2,
  guard: 2,
  jester: 1,
  innkeeper: 2,
  harlot: 2,
  leper: 1,
  'heretic-science': 1,
  'heretic-necro': 1,
  'heretic-alch': 1,
  cholera: 1,
  leprosy: 1,
  malaria: 1,
  black_pox: 1,
  bubonic_plague: 1,
};
